import seedcase_sprout as sp

# from .resource_properties import resource_properties

package_properties = sp.PackageProperties(
    ## Required:
    name="example-rhesus-monkeys",
    title="",
    description="",
    licenses=[
        sp.LicenseProperties(
            ## Required:
            name="",
            ## Optional:
            # path="",
            # title="",
        ),
    ],
    ## Optional:
    # homepage="",
    # contributors=[
    #    sp.ContributorProperties(
    #        ## Required:
    #        title="",
    #        ## Optional:
    #        path="",
    #        email="",
    #        given_name="",
    #        family_name="",
    #        organization="",
    #        roles=[""],
    #    ),
    # ],
    # keywords=[""],
    # image="",
    # sources=[
    #    sp.SourceProperties(
    #        ## Required:
    #        title="",
    #        ## Optional:
    #        path="",
    #        email="",
    #        version="",
    #    ),
    # ],
    # resources=[
    #     resource_properties,
    # ],
    ## Autogenerated:
    id="23025289-f416-40ae-a9d0-1160c8bb4999",
    version="0.1.0",
    created="2025-08-28T14:00:29+02:00",
)
